const FeatureConstants = {
  // audit features
  VIEW_AUDIT_TRAIL: 'VIEW_AUDIT_TRAIL',

  // projects page features
  PROTOCOL_MGMT: 'PROTOCOL_MGMT',

  CREATE_EDIT_PROJECT: 'CREATE_EDIT_PROJECT',
  TRANSFER_PROJECT: 'TRANSFER_PROJECT',
  LAUNCH_RUN: 'LAUNCH_RUN',
  VIEW_PROJECTS_RUNS: 'VIEW_PROJECTS_RUNS',
  VIEW_EDIT_RUN_DETAILS: 'VIEW_EDIT_RUN_DETAILS',
  SUBMIT_SUPPORT_TICKET: 'SUBMIT_SUPPORT_TICKET',
  MANAGE_IMPLEMENTATION_PROJECTS_IN_LAB: 'MANAGE_IMPLEMENTATION_PROJECTS_IN_LAB',

  // vendors page features
  KIT_MGMT: 'KIT_MGMT',
  VIEW_PUBLIC_MATERIALS: 'VIEW_PUBLIC_MATERIALS',

  // compound page features
  COMPOUND_MGMT: 'COMPOUND_MGMT',
  GET_REACTION: 'GET_REACTION',

  // device page features
  DEVICE_MGMT: 'DEVICE_MGMT',
  VIEW_DEVICES: 'VIEW_DEVICES',
  MANAGE_DEVICE_EVENTS: 'MANAGE_DEVICE_EVENTS',
  MANAGE_DEVICES: 'MANAGE_DEVICES',
  PROVISION_NEW_DEVICE: 'PROVISION_NEW_DEVICE',
  VIEW_PROVISIONED_DEVICES: 'VIEW_PROVISIONED_DEVICES',
  DEPLOY_DEVICE_DRIVERS: 'DEPLOY_DEVICE_DRIVERS',

  VIEW_COMPOUNDS: 'VIEW_COMPOUNDS',
  REGISTER_COMPOUND: 'REGISTER_COMPOUND',
  EDIT_COMPOUND: 'EDIT_COMPOUND',
  DOWNLOAD_COMPOUND: 'DOWNLOAD_COMPOUND',
  LINK_INVENTORY: 'LINK_INVENTORY',
  REGISTER_PUBLIC_COMPOUND: 'REGISTER_PUBLIC_COMPOUND',
  UPDATE_PUBLIC_COMPOUND: 'UPDATE_PUBLIC_COMPOUND',
  VIEW_LAB_COMPOUNDS: 'VIEW_LAB_COMPOUNDS',
  MANAGE_COMPOUNDS_IN_LAB: 'MANAGE_COMPOUNDS_IN_LAB',

  // inventory features
  INVENTORY_MGMT: 'INVENTORY_MGMT',
  MANAGE_CONTAINERS_IN_LAB: 'MANAGE_CONTAINERS_IN_LAB',
  VIEW_SAMPLE_CONTAINERS: 'VIEW_SAMPLE_CONTAINERS',
  DESTROY_CONTAINER_RESET_ALL_ALIQUOTS: 'DESTROY_CONTAINER_RESET_ALL_ALIQUOTS',
  MANAGE_CONTAINER_LOCATIONS: 'MANAGE_CONTAINER_LOCATIONS',
  MANAGE_IDT_ORDERS: 'MANAGE_IDT_ORDERS',
  DESTROY_CONTAINER: 'DESTROY_CONTAINER',
  MANAGE_STALE_CONTAINERS: 'MANAGE_STALE_CONTAINERS',
  EDIT_CONTAINER: 'EDIT_CONTAINER',
  CREATE_SAMPLE_SHIPMENTS: 'CREATE_SAMPLE_SHIPMENTS',
  CREATE_TEST_CONTAINERS: 'CREATE_TEST_CONTAINERS',
  LINK_COMPOUND_RESOURCE: 'LINK_COMPOUND_RESOURCE',
  REQUEST_SAMPLE_RETURN: 'REQUEST_SAMPLE_RETURN',
  MANAGE_CONTAINER_DESTRUCTION_REQUESTS: 'MANAGE_CONTAINER_DESTRUCTION_REQUESTS',
  TRANSFER_CONTAINER: 'TRANSFER_CONTAINER',

  // tisos feature
  MANAGE_TISOS: 'MANAGE_TISOS',

  // lab shipment features
  LAB_SHIPMENTS_MGMT: 'LAB_SHIPMENTS_MGMT',
  MANAGE_SAMPLE_RETURN_SHIPMENTS: 'MANAGE_SAMPLE_RETURN_SHIPMENTS',
  INTAKE_KITS_SHIPMENTS: 'INTAKE_KITS_SHIPMENTS',
  MANAGE_IMPLEMENTATION_SHIPMENTS: 'MANAGE_IMPLEMENTATION_SHIPMENTS',
  CHECKIN_SAMPLE_SHIPMENTS: 'CHECKIN_SAMPLE_SHIPMENTS',

  // runs page features
  RUN_MGMT: 'RUN_MGMT',
  RUN_STATE_MGMT: 'RUN_STATE_MGMT',
  VIEW_RUNS_IN_LABS: 'VIEW_RUNS_IN_LABS',
  VIEW_RUN_DETAILS: 'VIEW_RUN_DETAILS',
  CLAIM_RUN: 'CLAIM_RUN',
  CLONE_RUN_IN_LAB: 'CLONE_RUN_IN_LAB',
  RESERVE_DEVICE_FOR_EXECUTION: 'RESERVE_DEVICE_FOR_EXECUTION',
  MULTI_DEVICE_RUN_SCHEDULE: 'MULTI_DEVICE_RUN_SCHEDULE',
  CANCEL_RUN_IN_LAB: 'CANCEL_RUN_IN_LAB',

  // documentation page features
  DOCUMENTATION: 'DOCUMENTATION',

  // manage my organization features
  ADMINISTRATION: 'ADMINISTRATION',
  MANAGE_KITS_VENDORS_RESOURCES: 'MANAGE_KITS_VENDORS_RESOURCES',

  // manage lab kit orders
  MANAGE_KIT_ORDERS: 'MANAGE_KIT_ORDERS',

  // beta features
  CIRRUS: 'CIRRUS',
  MANAGE_WORKFLOWS: 'MANAGE_WORKFLOWS',
  VIEW_WORKFLOWS: 'VIEW_WORKFLOWS',
  MANAGE_EXPERIMENTS: 'MANAGE_EXPERIMENTS',
  VIEW_EXPERIMENTS: 'VIEW_EXPERIMENTS',

  // prime directive page feature
  SUBMIT_INSTRUCTIONS_TO_EXECUTE: 'SUBMIT_INSTRUCTIONS_TO_EXECUTE',

  // Package protocol features
  VIEW_PACKAGE_PROTOCOLS: 'VIEW_PACKAGE_PROTOCOLS',
  CREATE_PACKAGE_PROTOCOL: 'CREATE_PACKAGE_PROTOCOL',
  DELETE_DATASET: 'DELETE_DATASET',
  VIEW_PRICE_BREAKDOWN: 'VIEW_PRICE_BREAKDOWN',
  PUBLISH_RELEASE_PACKAGE_PROTOCOL: 'PUBLISH_RELEASE_PACKAGE_PROTOCOL',
  UPLOAD_NEW_RELEASE_DESTROY_PACKAGE_PROTOCOL: 'UPLOAD_NEW_RELEASE_DESTROY_PACKAGE_PROTOCOL',

  // shipments page feature
  SHIPMENTS_MGMT: 'SHIPMENTS_MGMT',
  REQUEST_SAMPLE_CONTAINERS: 'REQUEST_SAMPLE_CONTAINERS',
  VIEW_IN_TRANSIT_SAMPLE_CONTAINERS_SHIPMENTS: 'VIEW_IN_TRANSIT_SAMPLE_CONTAINERS_SHIPMENTS',
  VIEW_SAMPLE_RETURN_SHIPMENTS: 'VIEW_SAMPLE_RETURN_SHIPMENTS',
  VIEW_INTAKEKIT_SHIPMENTS: 'VIEW_INTAKEKIT_SHIPMENTS',

  // chemical reaction management
  EDIT_SUBMIT_REACTION: 'EDIT_SUBMIT_REACTION',
  CREATE_REACTION: 'CREATE_REACTION',

  // library feature
  VIEW_LIBRARIES: 'VIEW_LIBRARIES',
  EDIT_LIBRARY: 'EDIT_LIBRARY',

  // batch features
  MANAGE_BATCHES_IN_LAB: 'MANAGE_BATCHES_IN_LAB',
  VIEW_BATCHES: 'VIEW_BATCHES',

  // platform features
  MANAGE_ORGS_GLOBAL: 'MANAGE_ORGS_GLOBAL',
  CREATE_DELETE_ORGANIZATION: 'CREATE_DELETE_ORGANIZATION',
  VIEW_USERS_GLOBAL: 'VIEW_USERS_GLOBAL',
  MANAGE_USERS_GLOBAL: 'MANAGE_USERS_GLOBAL',
  TRANSFER_OWNERSHIP_GLOBAL: 'TRANSFER_OWNERSHIP_GLOBAL',

  // billing admin platform features
  VIEW_INVOICES_GLOBAL: 'VIEW_INVOICES_GLOBAL',
  MANAGE_INVOICES_GLOBAL: 'MANAGE_INVOICES_GLOBAL',
  APPROVE_PURCHASE_ORDER: 'APPROVE_PURCHASE_ORDER',

  // Customer Success features
  CAN_REMOVE_USERS_FROM_PLATFORM: 'CAN_REMOVE_USERS_FROM_PLATFORM',

  // mixture features
  MANAGE_MIXTURES: 'MANAGE_MIXTURES',
  VIEW_MIXTURES: 'VIEW_MIXTURES',

  // Implementation project feature
  MANAGE_IMPLEMENTATION_PROJECTS_IN_LAB: 'MANAGE_IMPLEMENTATION_PROJECTS_IN_LAB',

  // Chemical reactions Micro-app service features
  VIEW_REACTION_TEMPLATE: 'VIEW_REACTION_TEMPLATE',
  EDIT_REACTION_TEMPLATE: 'EDIT_REACTION_TEMPLATE',
  CREATE_REACTION_TEMPLATE: 'CREATE_REACTION_TEMPLATE',

  // job shipment API features
  JOB_MANAGEMENT: 'JOB_MANAGEMENT',
  SUBMIT_JOB: 'SUBMIT_JOB',
  VIEW_JOB_STATUS: 'VIEW_JOB_STATUS'
};

export default FeatureConstants;
